global using System.Text;
global using Microsoft.AspNetCore.Components;
global using Microsoft.AspNetCore.Components.Forms;
global using Microsoft.JSInterop;
global using MudBlazor;
global using PKHeX.Core;
global using Pkmds.Rcl.Components;
global using Pkmds.Rcl.Extensions;
global using Pkmds.Rcl.Services;
