using System.Runtime.InteropServices;
using System.Runtime.InteropServices.ComTypes;
using Microsoft.Win32;
using PKHeX.Core;

// TODO: Uncomment once Microsoft.Web.WebView2 is added to Directory.Packages.props
// using Microsoft.Web.WebView2.WinForms;

namespace Pkmds.Preview.Windows;

// -----------------------------------------------------------------------------------
// Stub: Windows Shell Preview Handler
//
// A Windows preview handler is an in-process COM server loaded by prevhost.exe when
// the user selects a file in Explorer with the Preview Pane open. This stub shows
// the shape of the implementation; the TODO items below describe what remains.
//
// COM class identity — MUST be unique per handler.
// TODO: Replace the placeholder GUID with a freshly generated one:
//   PowerShell:  [guid]::NewGuid()
//   Visual Studio: Tools > Create GUID
// -----------------------------------------------------------------------------------
[ComVisible(true)]
[Guid("A1B2C3D4-E5F6-7890-ABCD-EF1234567890")]  // TODO: replace with real GUID
[ClassInterface(ClassInterfaceType.None)]
public sealed class PkmdsPreviewHandler : IPreviewHandler, IInitializeWithFile, IDisposable
{
    private string? _filePath;
    private nint _parentHwnd;
    private RECT _previewRect;

    // TODO: Declare WebView2 field:
    //   private WebView2? _webView;
    //   private bool _webViewReady;

    // ── IInitializeWithFile ────────────────────────────────────────────────────────

    public void Initialize(string pszFilePath, uint grfMode)
    {
        _filePath = pszFilePath;
    }

    // ── IPreviewHandler ────────────────────────────────────────────────────────────

    public void SetWindow(nint hwnd, ref RECT prc)
    {
        _parentHwnd = hwnd;
        _previewRect = prc;

        // TODO: Create the WebView2 control as a child of hwnd.
        //
        // WebView2 initialization is async; DoPreview() may be called before
        // CoreWebView2 is ready. A simple pattern:
        //
        //   _webView = new WebView2();
        //   _webView.SetBounds(prc.ToRectangle());
        //   _webView.CoreWebView2InitializationCompleted += (_, _) =>
        //   {
        //       _webViewReady = true;
        //       RenderIfReady();
        //   };
        //   NativeMethods.SetParent(_webView.Handle, hwnd);
        //   _ = _webView.EnsureCoreWebView2Async();
    }

    public void SetRect(ref RECT prc)
    {
        _previewRect = prc;
        // TODO: _webView?.SetBounds(prc.ToRectangle());
    }

    public void DoPreview()
    {
        // TODO: Call RenderIfReady() once _webViewReady is true, or queue a render.
        //
        // The actual rendering entry point — see RenderIfReady() below.
    }

    public void Unload()
    {
        _filePath = null;
        // TODO: _webView?.Dispose(); _webView = null; _webViewReady = false;
    }

    public void SetFocus()
    {
        // TODO: _webView?.Focus();
    }

    public void QueryFocus(out nint phwnd)
    {
        phwnd = NativeMethods.GetFocus();
    }

    // Return S_FALSE (1) to tell the host we did not handle the keystroke.
    public int TranslateAccelerator(ref MSG pmsg) => 1;

    // ── Rendering ─────────────────────────────────────────────────────────────────

    private void RenderIfReady()
    {
        // TODO: Guard on _webViewReady && _filePath != null.

        if (_filePath is null)
            return;

        var ext = Path.GetExtension(_filePath).ToLowerInvariant();
        var bytes = File.ReadAllBytes(_filePath);

        var html = ext == ".sav"
            ? SaveUtil.TryGetSaveFile(bytes, out var sav)
                ? HtmlRenderer.RenderSave(sav)
                : ErrorHtml("Unable to read save file.")
            : EntityFormat.GetFromBytes(bytes) is { } pkm
                ? HtmlRenderer.RenderPkm(pkm)
                : ErrorHtml("Unable to read entity file.");

        // TODO: _webView!.CoreWebView2.NavigateToString(html);
        _ = html; // suppress unused-variable warning until WebView2 is wired up
    }

    private static string ErrorHtml(string message) =>
        $"<!doctype html><html><body style=\"font:13px Segoe UI,sans-serif;padding:16px\">" +
        $"<p>{System.Net.WebUtility.HtmlEncode(message)}</p></body></html>";

    // ── IDisposable ───────────────────────────────────────────────────────────────

    public void Dispose()
    {
        // TODO: _webView?.Dispose();
    }

    // ── Registration helpers ───────────────────────────────────────────────────────

    // Called by regsvr32 (DllRegisterServer / DllUnregisterServer are generated by
    // EnableComHosting; these helpers write the per-extension shell integration keys).
    //
    // Usage (admin PowerShell, from the output directory):
    //   regsvr32 PkmdsPreview.comhost.dll
    //   [PkmdsPreviewHandler]::RegisterShellExtension()
    //
    // TODO: Decide whether to run this from a post-build script, an installer, or
    // a small host EXE so users don't need to call it manually.

    private static readonly Guid HandlerGuid = new("A1B2C3D4-E5F6-7890-ABCD-EF1234567890"); // TODO: match class GUID above

    // IPreviewHandler shell-extension IID — fixed by Windows, do not change.
    private const string PreviewHandlerIid = "{8895b1c6-b41f-4c1c-a562-0d564250836f}";

    // Extensions to register. Expand as more formats are validated.
    private static readonly string[] Extensions =
        [".pk1", ".pk2", ".pk3", ".pk4", ".pk5", ".pk6", ".pk7", ".pk8", ".pk9",
         ".pa8", ".pb7", ".pb8", ".sav"];

    public static void RegisterShellExtension()
    {
        var guid = $"{{{HandlerGuid}}}";
        foreach (var ext in Extensions)
        {
            using var key = Registry.ClassesRoot.CreateSubKey(
                $@"{ext}\ShellEx\{PreviewHandlerIid}");
            key.SetValue(null, guid);
        }
    }

    public static void UnregisterShellExtension()
    {
        foreach (var ext in Extensions)
        {
            Registry.ClassesRoot.DeleteSubKeyTree(
                $@"{ext}\ShellEx\{PreviewHandlerIid}", throwOnMissingSubKey: false);
        }
    }
}

// ── Minimal COM interface declarations ────────────────────────────────────────────
//
// These match the Windows SDK definitions. If you add CsWin32 to the project
// (NuGet: Microsoft.Windows.CsWin32 + Microsoft.Windows.SDK.Win32Metadata), add
// the names to NativeMethods.txt and delete these manual definitions.

[ComImport]
[InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
[Guid("8895b1c6-b41f-4c1c-a562-0d564250836f")]
public interface IPreviewHandler
{
    void SetWindow(nint hwnd, ref RECT prc);
    void SetRect(ref RECT prc);
    void DoPreview();
    void Unload();
    void SetFocus();
    void QueryFocus(out nint phwnd);
    [PreserveSig] int TranslateAccelerator(ref MSG pmsg);
}

[ComImport]
[InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
[Guid("b7d14566-0509-4cce-a71f-0a554233bd9b")]
public interface IInitializeWithFile
{
    void Initialize([MarshalAs(UnmanagedType.LPWStr)] string pszFilePath, uint grfMode);
}

[StructLayout(LayoutKind.Sequential)]
public struct RECT
{
    public int Left, Top, Right, Bottom;

    // TODO: Uncomment once UseWindowsForms is active and WebView2 is added
    // public System.Drawing.Rectangle ToRectangle() =>
    //     System.Drawing.Rectangle.FromLTRB(Left, Top, Right, Bottom);
}

[StructLayout(LayoutKind.Sequential)]
public struct MSG
{
    public nint hwnd;
    public uint message;
    public nuint wParam;
    public nint lParam;
    public uint time;
    public int ptX, ptY;
}

internal static class NativeMethods
{
    [DllImport("user32.dll")]
    internal static extern nint GetFocus();

    [DllImport("user32.dll")]
    internal static extern nint SetParent(nint hWndChild, nint hWndNewParent);
}
