global using KristofferStrube.Blazor.FileSystemAccess;
global using Microsoft.AspNetCore.Components;
global using MudBlazor.Services;
global using PKHeX.Core;
global using Pkmds.Web.Client;
global using Pkmds.Web.Client.Services;
global using Pkmds.Web.Client.Services.Models;
global using Pkmds.Web.Components;
global using Pkmds.Web.Services;
